DB_USERNAME: postgres
DB_PASSWORD: 12345
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: idonatedb

MEDIA_SERVER_PATH: src/main/resources/filestorage/idata-medias/
MEDIA_BASE_URI=http: http://localhost:8080/media
MEDIA_CLIENT_PATH: /media/**

GMAIL_USERNAME: srengchipor99@gmail.com
GMAIL_PASSWORD: cmyy qama rcbk brqu
EMAIL_SENDER: iDonate