spring:
  application:
    name: ledgerlift

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  jpa:
    hibernate:
      ddl-auto:
        create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    senderName: ${EMAIL_SENDER}
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true

logging:
  level:
    org.springframework.mail: DEBUG

server:
  port: 8080

fabric:
  wallet:
    config-path: wallets
  network:
    channel: mychannel
    discovery: true
    config-path: ./fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json
  ca:
    admin:
      username: admin
      password: adminpw
    org1:
      name: Org1
      mspId: Org1MSP
      caUrl: https://localhost:7054
      certificatePath: ./fabric-samples/test-network/organizations/fabric-ca/org1/ca-cert.pem
    tls:
      enabled: true

media:
  server-path: ${MEDIA_SERVER_PATH} 
  client-path: ${MEDIA_CLIENT_PATH}
  base-uri: ${MEDIA_BASE_URI=http}

keys:
  access-private-token: keys/access-private
  access-public-token: keys/access-public
  refresh-public-token: keys/refresh-public
  refresh-private-token: keys/refresh-private

springdoc:
  swagger-ui:
    path: /ledgeraiser-api-ui.html
    url: /ledgeraiser-api-docs
  api-docs:
    path: /ledgeraiser-api-docs

