spring:
  application:
    name: ledgerlift

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  jpa:
    hibernate:
      ddl-auto:
        create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

fabric:
  wallet:
    config-path: wallets
  network:
    channel: mychannel
    discovery: true
    config-path: ./fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/connection-org1.json
  ca:
    admin:
      username: admin
      password: adminpw
    org1:
      name: Org1
      mspId: Org1MSP
      caUrl: "https://localhost:7054"
      certificatePath: ./fabric-samples/test-network/organizations/fabric-ca/org1/ca-cert.pem
    tls:
      enabled: true



