spring:
  application:
    name: ledgerlift

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  jpa:
    hibernate:
      ddl-auto:
        create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

